"""
labat/routers/leads_routes.py — Lead Ads endpoints.

LABAT owns leads (they come from paid ads — money in = leads out).
Shania's page token is used to list forms; LABAT's system user token
fetches the actual lead submissions.

GET  /api/labat/leads/forms                  — list lead gen forms on the Page
GET  /api/labat/leads/forms/{form_id}        — form details + questions
GET  /api/labat/leads/forms/{form_id}/leads  — submissions for a form
GET  /api/labat/leads/{lead_id}              — single lead with parsed fields
GET  /api/labat/leads/ad/{ad_id}             — leads from a specific ad
GET  /api/labat/leads/cost                   — cost-per-lead summary from insights
"""

from __future__ import annotations

import logging
import os
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query

from src.labat.auth import require_admin
from src.labat.services import leads_service
from src.labat.meta_client import MetaAPIError

logger = logging.getLogger("labat.leads_routes")

router = APIRouter(prefix="/api/labat/leads", tags=["labat-leads"])


@router.get("/forms")
async def list_lead_forms(
    page_id: Optional[str] = Query(None, description="Override default page ID"),
    limit: int = Query(25, ge=1, le=100),
    _=Depends(require_admin),
):
    """List all lead gen forms attached to the Page (Shania manages the page)."""
    try:
        return await leads_service.list_lead_forms(page_id=page_id, limit=limit)
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


@router.get("/forms/{form_id}")
async def get_lead_form(form_id: str, _=Depends(require_admin)):
    """Get full details for a lead gen form including its questions."""
    try:
        return await leads_service.get_lead_form(form_id)
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


@router.get("/forms/{form_id}/leads")
async def get_form_leads(
    form_id: str,
    limit: int = Query(50, ge=1, le=100),
    after: Optional[str] = Query(None, description="Pagination cursor"),
    since: Optional[str] = Query(None, description="Filter from date (ISO 8601)"),
    until: Optional[str] = Query(None, description="Filter to date (ISO 8601)"),
    _=Depends(require_admin),
):
    """
    Fetch lead submissions for a form.
    Returns field_data with name/email/phone/etc based on your form questions.
    """
    try:
        return await leads_service.get_leads_from_form(
            form_id=form_id,
            limit=limit,
            after=after,
            since=since,
            until=until,
        )
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


@router.get("/ad/{ad_id}")
async def get_ad_leads(
    ad_id: str,
    limit: int = Query(50, ge=1, le=100),
    after: Optional[str] = Query(None),
    _=Depends(require_admin),
):
    """Fetch leads generated by a specific ad."""
    try:
        return await leads_service.get_leads_from_ad(ad_id=ad_id, limit=limit, after=after)
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


@router.get("/cost")
async def lead_cost_summary(
    campaign_id: Optional[str] = Query(None, description="Scope to a campaign; omit for account-level"),
    date_preset: str = Query("last_30d"),
    _=Depends(require_admin),
):
    """
    Cost-per-lead summary from LABAT ad insights.
    Shows how much money was spent to acquire each lead.
    """
    try:
        return await leads_service.get_lead_cost_summary(
            campaign_id=campaign_id,
            date_preset=date_preset,
        )
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


@router.get("/{lead_id}")
async def get_lead(lead_id: str, _=Depends(require_admin)):
    """
    Get a single lead submission with parsed field data
    (name, email, phone, custom questions, etc.).
    """
    try:
        return await leads_service.get_lead(lead_id)
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


# ── Lead Form Creation ────────────────────────────────────────────────────────

from pydantic import BaseModel, Field
from typing import List, Dict, Any


class CreateLeadFormRequest(BaseModel):
    page_id: str = Field(..., description="Facebook Page ID to attach the form to")
    name: str = Field(..., min_length=1, max_length=200)
    privacy_policy_url: str
    thank_you_url: Optional[str] = None
    product: Optional[str] = Field(None, description="Brand/product name (wihy, communitygroceries, etc.). Auto-injects qualifying questions when questions is omitted.")
    questions: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Form fields. If omitted and product is set, qualifying questions are loaded from strategy_rules.",
    )


@router.post("/forms")
async def create_lead_form(body: CreateLeadFormRequest, _=Depends(require_admin)):
    """Create a lead gen form on a Facebook Page.

    If ``questions`` is omitted and ``product`` is provided, qualifying
    questions are loaded automatically from strategy_rules presets.
    Standard contact fields (EMAIL, FIRST_NAME) are always prepended.
    """
    from src.labat.services.strategy_rules import get_lead_form_preset

    questions = body.questions
    if questions is None:
        base = [{"type": "EMAIL"}, {"type": "FIRST_NAME"}]
        if body.product:
            preset = get_lead_form_preset(body.product)
            questions = base + preset
        else:
            questions = base + [{"type": "LAST_NAME"}]

    try:
        return await leads_service.create_lead_form(
            page_id=body.page_id,
            name=body.name,
            questions=questions,
            privacy_policy_url=body.privacy_policy_url,
            thank_you_url=body.thank_you_url,
        )
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


# ── Lead Gen TOS ──────────────────────────────────────────────────────────────


@router.post("/tos/{page_id}")
async def accept_tos(page_id: str, _=Depends(require_admin)):
    """Accept Facebook Lead Ads TOS for a page."""
    try:
        return await leads_service.accept_leadgen_tos(page_id)
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


@router.get("/tos/{page_id}")
async def get_tos(page_id: str, _=Depends(require_admin)):
    """Check Lead Gen TOS status for a page."""
    try:
        return await leads_service.get_leadgen_tos(page_id)
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))


# ── Lead Sync (Meta → Firestore → Email) ──────────────────────────────────────

from src.labat.services import lead_sync_service

# Brand scope for this instance
_BRAND_SCOPE = (os.getenv("LABAT_BRAND_SCOPE", "all") or "all").strip().lower()


@router.post("/sync")
async def sync_leads(
    form_id: Optional[str] = Query(None, description="Sync a specific form; omit to sync all"),
    brand: Optional[str] = Query(None, description="Override brand detection"),
    _=Depends(require_admin),
):
    """
    Pull new leads from Facebook Lead Forms → store in Firestore → send welcome email.
    Call periodically (cron) or manually after launching lead ads.

    When LABAT_BRAND_SCOPE is set, defaults the brand to this instance's scope.
    """
    # Default brand to this instance's scope if not explicitly provided
    effective_brand = brand or (_BRAND_SCOPE if _BRAND_SCOPE != "all" else None)
    try:
        if form_id:
            result = await lead_sync_service.sync_leads_from_form(
                form_id=form_id, brand=effective_brand
            )
        else:
            result = await lead_sync_service.sync_all_forms()
        return result
    except MetaAPIError as e:
        raise HTTPException(status_code=e.status_code or 502, detail=str(e))
    except Exception as e:
        logger.error("Lead sync failed: %s", e, exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
